### ISSUE TITLE
Fix retina images.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/api#22]
There is an issue with retina images that was introduced in 300c920.  Basically, using `hidpi` mixin requires compass's `image-width` and `image-height` mixins [here](https://github.com/trek/ember-api/blob/2095d9e7ff6f12c89062968435ee0a46aca5726e/app/styles/mixins/_hidpi.scss#L23).

**Comment by rwjblue** [comment]
@gregone - Would you happen to have time to look into this?

**Comment by gregone** [comment]
@rwjblue will do

**Comment by trek** [comment]
@gregone is this still an issue? This will become a blocker soon.

**Comment by gregone** [comment]
@trek see #24
