### ISSUE TITLE
Help setting up the project

### ISSUE THREAD

**Issue by purezen** [emberjs/api#26]
Hi guys, I would like to contribute to the project for the search implementation. 
Though, I need some help getting started. Have cloned the repo but would like some clarification of its arguments. What do the lib-dir and execution-dir refer to?
If I am right, an instance of this app would be http://emberjs.com/api/?

Btw, have made a basic app using ember-cli a while back.

**Comment by trek** [comment]
per the README "lib-dir (path) local path to the library documented with YUIDoc e.g. /usr/yourname/code/ember.js", "execution-dir (path, default lib-dir) local path to the directory where yuidoc should execute: e.g. '/usr/yourname/code/ember.js/docs'"
