### ISSUE TITLE
Methods of Used Mixins not Included?

### ISSUE THREAD

**Issue by IanVS** [emberjs/api#27]
I noticed that `toArray()` is not included as a method of `DS.ManyArray`, even though it uses `Ember.MutableArray`.  When the `inherited` checkbox is checked, shouldn't `toArray()` be shown as a method that can be used on ManyArray?  Or are "used" mixins not inherited by design?  See further discussion here: https://github.com/emberjs/data/issues/2665

**Comment by trek** [comment]
Before 1.13, there was no way to know what version of Ember matched to what version of ember-data, so it was not possible to look up its super class.
