### ISSUE TITLE
Missing LICENSE or COPYING

### ISSUE THREAD

**Issue by omouse** [emberjs/api#32]
The license terms are missing. In the package.json it appears the code is licensed under the MIT license however the license is not included in the repository nor is it clearly labeled in the README.md or in any other files.

I would like to look at the code and potentially adapt some of it for use in another free/open source project.

**Comment by locks** [comment]
@trek @rwjblue MIT?

**Comment by rwjblue** [comment]
Ya, should be MIT

Robert Jackson

-- twitter: rwjblue
-- github: rjackson
