### ISSUE TITLE
Use YUIDoc Branch

### ISSUE THREAD

**Issue by trek** [emberjs/api#36]
https://github.com/yui/yuidoc/pull/372

Should increase doc builds by 10-100x

**Comment by rwjblue** [comment]
per https://github.com/yui/yuidoc/pull/372#issuecomment-172528880, it was released as v0.10.0

**Comment by rwjblue** [comment]
Closed by https://github.com/trek/ember-cli-yuidoc-converter/pull/4.

**Comment by trek** [comment]
Closing in favor of https://github.com/trek/ember-cli-yuidoc-converter/pull/4
