### ISSUE TITLE
Finish Up

### ISSUE THREAD

**Issue by trek** [emberjs/api#5]
### App
- [x] correct github links [@trek]
- [x] implement Inherited/Protected/Private/Deprecated filtering [@trek]
- [x] add waypoint for class description area [@trek]
- [x] prune unused CSS (meta issue #15)
- [x] prune unused JSON [@trek]
- [x] remove hard-coded data.json location (so we can generate docs for any library we want)
- [x] add navigation to other libraries [@trek]
- [x] add navigation to other revs from within a library [@trek]
- [x] separate notion of doc build SHA and release target (e.g. doc rev 1.1.3 might have spelling error fixed in SHA `#decafbebad`. We should still note that the documented rev is 1.1.3's public API but the build SHA was `#decafbebad` [@trek]
- [x] move build script to ember addon [@trek]
- [x] implement the "Back to top" waypoint link [@trek]

- [x] move all layout markup into `application.hbs` [@trek]
- [x] tests and such

### Deploy Process
- [x] setup divshot project
- [x] plan/document folder structure
- [x] automate site generation, copying to deploy project, and publishing

**Comment by trek** [comment]
@rwjblue I don't see a way to push folders. Divshot seems to expect one ember app === one divshot app?

**Comment by knownasilya** [comment]
Ping @rwjblue

**Comment by trek** [comment]
ooops! Apologies, Robert and I talked about this offline. We'd have a single divshot project to represent all deploys. It would be basically a read-only archive of the `dist` folder of this project.
