### ISSUE TITLE
Running ember s automatically changes git branch to master

### ISSUE THREAD

**Issue by MarkMT** [emberjs/api#71]
I'm seeing something that seems weird... 

I have a fork of emberjs/data and a local clone of that fork. I've created a local branch and made some edits to the `DS.Store` API documentation.

I also have a local clone of emberjs/api and followed the instructions to generate the docs for ember-data. If I do this with the master branch of ember-data checked out everything works fine. I can browse the docs as expected. I've tried making edits on that branch and again everything works fine; I can see my edits as expected.

However if I check out my development branch and do the same thing, when I run `ember s` my edits on that branch don't show up in the rendered docs, and it turns out that the reason is that the repo is switching automatically to the master branch.

Is this normal behavior? Is this something emberjs/api is doing or is there something else weird that I have going on?

**Comment by MarkMT** [comment]
BTW I've tried the same thing on a cloned fork of emberjs/ember.js and I see the same behavior.

**Comment by acorncom** [comment]
@MarkMT This was an experiment that we've ended up mostly abandoning.  Are you wanting to run the api docs locally on your machine or were you wanting to help get this wrapped up?  If you want api docs locally you'd need to use the https://github.com/emberjs/website repo.  If you're wanting to help us get it finished off, we'd love to get you working on the current repo at https://github.com/ember-learn/ember-api-docs (use the milestones as guides for what we'd love to see prioritized).

Thanks!

**Comment by MarkMT** [comment]
Thanks @acorncom. I was just trying to render the docs locally so I could test out some doc changes I planned to put in a PR. I think I found this repo via google so I wasn't actually aware of emberjs/website but I'll give that a go. Sorry I wish I could help with ember-api-docs, but in my current circumstances contributing to documentation is maxing out what I can afford time for.

**Comment by acorncom** [comment]
> Sorry I wish I could help with ember-api-docs, but in my current circumstances contributing to documentation is maxing out what I can afford time for.

@MarkMT Fully understood, no problem there 😄
